### ISSUE TITLE
FAIL: src/browser/App.test.tsx

### ISSUE THREAD

**Issue by DaxGoon** [arabold/serverless-react-boilerplate#15]
Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
    If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

      at Parser._raise (node_modules/@babel/parser/src/parser/error.js:60:45)
      at Parser.raiseWithData (node_modules/@babel/parser/src/parser/error.js:55:17)
      at Parser.expectOnePlugin (node_modules/@babel/parser/src/parser/util.js:157:18)
      at Parser.parseExprAtom (node_modules/@babel/parser/src/parser/expression.js:1180:18)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/src/parser/expression.js:563:23)
      at Parser.parseUpdate (node_modules/@babel/parser/src/parser/expression.js:543:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/src/parser/expression.js:527:17)
      at Parser.parseExprOps (node_modules/@babel/parser/src/parser/expression.js:343:23)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/src/parser/expression.js:308:23)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/src/parser/expression.js:263:21)

Suggested solution (by the error message) does not solve the error.

**Comment by arabold** [comment]
@DaxGoon , what exactly am I looking at? The current configuration provided by the boilerplate should work out of the box. The `.babelrc` that is included in the repo is already using `@babel/preset-react` and shouldn't be any need to add the `@babel/plugin-syntax/jsx` manually as well. What problem are you trying to solve?

Side note: I've just updated all dependencies but React in the latest version of this repo. Pull the changes, maybe it fixes your issue already?

**Comment by DaxGoon** [comment]
I encountered the problem after trying to incorporate this setup with a rather complex application with subdirectories and multi page setup with react-router. On 2 Feb 2021 20.25, Andre Rabold <notifications@github.com> wrote:
@DaxGoon , what exactly am I looking at? The current configuration provided by the boilerplate should work out of the box. The .babelrc that is included in the repo is already using @babel/preset-react and shouldn't be any need to add the @babel/plugin-syntax/jsx manually as well. What problem are you trying to solve?

**Comment by arabold** [comment]
Hard to know what's going on without seeing it. Can you share more details about your setup or maybe an example Codebox that I can run myself? 

But if it helps, I have also added a PR that shows how to integrate React Router: https://github.com/arabold/serverless-react-boilerplate/pull/16

**Comment by arabold** [comment]
I'm going to close this for now. The latest update of the boilerplate contains some cleanup of the babel config and some other simplifications. It might help but without additional details it's impossible for me to help debugging this issue.
