### ISSUE TITLE
Deployment Error: Access Denied

### ISSUE THREAD

**Issue by mstfldmr** [arabold/serverless-react-boilerplate#34]
I am following the guidelines at https://www.serverless.com/blog/react-js-on-aws-lambda. `npx sls deploy` command creates the Cloudformation stack successfully but the command returns **Access Denied** error.

```
(base) bcd07414e341:ServerlessReact mustafa$ npx sls deploy

Deploying serverless-react-boilerplate to stage dev (us-east-1)

> serverless-react-boilerplate@0.1.0 build:browser
> webpack --config webpack.browser.config.js --mode production

assets by info 291 KiB [immutable]
  assets by chunk 4.87 KiB (name: main)
    asset main.f73cf1e4.js 4.38 KiB [emitted] [immutable] [minimized] (name: main) 1 related asset
    asset main.4a854c81.css 499 bytes [emitted] [immutable] (name: main) 1 related asset
  asset vendor.ae97a551.js 284 KiB [emitted] [immutable] [minimized] [big] (name: vendor) (id hint: vendor) 2 related assets
  asset runtime.3553f038.js 1.22 KiB [emitted] [immutable] [minimized] (name: runtime) 1 related asset
  asset components.bc92458d.js 424 bytes [emitted] [immutable] [minimized] (name: components) (id hint: components) 1 related asset
assets by path *.json 457 bytes
  asset manifest.json 286 bytes [emitted] [from: public/manifest.json] [copied]
  asset stats.json 171 bytes [emitted]
asset favicon.ico 3.78 KiB [emitted] [from: public/favicon.ico] [copied]
Entrypoint main [big] 291 KiB (488 KiB) = runtime.3553f038.js 1.22 KiB vendor.ae97a551.js 284 KiB components.bc92458d.js 424 bytes main.4a854c81.css 499 bytes main.f73cf1e4.js 4.38 KiB 5 auxiliary assets
orphan modules 9.06 KiB (javascript) 1.83 KiB (runtime) [orphan] 16 modules
runtime modules 3.02 KiB 5 modules
modules by path ./node_modules/core-js/ 503 KiB 479 modules
modules by path ./src/ 5.52 KiB (javascript) 452 bytes (css/mini-extract) 5 modules
modules by path ./node_modules/react/ 6.48 KiB
  ./node_modules/react/index.js 190 bytes [built] [code generated]
  ./node_modules/react/cjs/react.production.min.js 6.3 KiB [built] [code generated]
modules by path ./node_modules/react-dom/ 119 KiB
  ./node_modules/react-dom/index.js 1.33 KiB [built] [code generated]
  ./node_modules/react-dom/cjs/react-dom.production.min.js 118 KiB [built] [code generated]
modules by path ./node_modules/scheduler/ 4.91 KiB
  ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
  ./node_modules/scheduler/cjs/scheduler.production.min.js 4.72 KiB [built] [code generated]
./node_modules/regenerator-runtime/runtime.js 24.3 KiB [built] [code generated]
./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
webpack 5.72.0 compiled successfully in 2921 ms
Environment: darwin, node 16.15.0, framework 3.14.0 (local), plugin 6.2.1, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Access Denied

2 deprecations found: run 'serverless doctor' for more details

✖ Stack serverless-react-boilerplate-dev failed to deploy (145s)
Environment: darwin, node 16.15.0, framework 3.14.0 (local), plugin 6.2.1, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Command failed: npx sls s3deploy --stage dev
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at /Users/mustafa/workspace/ServerlessReact/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:86:41
    at handleSubProcessSync (/Users/mustafa/workspace/ServerlessReact/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:32:15)
    at childProcess.execSync (/Users/mustafa/workspace/ServerlessReact/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:85:11)
    at Scripts.execute (/Users/mustafa/workspace/ServerlessReact/node_modules/serverless-plugin-scripts/lib/index.js:113:35)
    at Scripts.runHook (/Users/mustafa/workspace/ServerlessReact/node_modules/serverless-plugin-scripts/lib/index.js:108:12)
    at PluginManager.runHooks (/Users/mustafa/workspace/ServerlessReact/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginManager.invoke (/Users/mustafa/workspace/ServerlessReact/node_modules/serverless/lib/classes/plugin-manager.js:564:9)
    at async PluginManager.run (/Users/mustafa/workspace/ServerlessReact/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/mustafa/workspace/ServerlessReact/node_modules/serverless/lib/serverless.js:174:5)
    at async /Users/mustafa/workspace/ServerlessReact/node_modules/serverless/scripts/serverless.js:765:9

2 deprecations found: run 'serverless doctor' for more details
```

**Comment by BranBer** [comment]
I'm getting the same issue too. Any updates?

**Comment by bymoud** [comment]
I had the same issue. And following the answers [here](https://stackoverflow.com/questions/71080354/getting-the-bucket-does-not-allow-acls-error) helped overcome it.
